name: vickye
favicon: null
layout_spectrum: 0.4945
typography_spectrum: 0.50061
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2dfd5'
    - '#8ba3ac'
    - '#1b1e2c'
    - '#d78022'
    - '#0364b2'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.9375
  rhythmicContrast: 0.22684320737607777
purpose: []
